licenses(["notice"])
package(default_visibility = ["//third_party/rules_closure/closure:__subpackages__"])

load("//third_party/rules_closure/closure:defs.bzl", "closure_js_library")

closure_js_library(
    name = "phantomjs",
    externs = ["phantom.js"],
)
